### ISSUE TITLE
TypeError downloading from Ensembl

### ISSUE THREAD

**Issue by jma1991** [simonvh/genomepy#30]
I am getting an error when I try to download genomes from Ensembl (version 0.5.2 from bioconda)

Human:
```
$ genomepy install -g data/genomes --annotation GRCh38.p12 Ensembl
/home/s1437643/conda/lib/python3.6/site-packages/norns-0.1.2-py2.7.egg/norns/cfg.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "/home/s1437643/conda/bin/genomepy", line 11, in <module>
    load_entry_point('genomepy==0.5.2', 'console_scripts', 'genomepy')()
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/cli.py", line 38, in install
    regex=regex, invert_match=not(match), annotation=annotation)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/functions.py", line 197, in install_genome
    invert_match=invert_match)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/provider.py", line 132, in download_genome
    dbname, link = self.get_genome_download_link(name, mask=mask, version=version)
TypeError: 'NoneType' object is not iterable
```

Mouse:
```
$ genomepy install -g data/genomes --annotation GRCm38.p6 Ensembl
/home/s1437643/conda/lib/python3.6/site-packages/norns-0.1.2-py2.7.egg/norns/cfg.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "/home/s1437643/conda/bin/genomepy", line 11, in <module>
    load_entry_point('genomepy==0.5.2', 'console_scripts', 'genomepy')()
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/cli.py", line 38, in install
    regex=regex, invert_match=not(match), annotation=annotation)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/functions.py", line 197, in install_genome
    invert_match=invert_match)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/provider.py", line 132, in download_genome
    dbname, link = self.get_genome_download_link(name, mask=mask, version=version)
TypeError: 'NoneType' object is not iterable
```

Zebrafish:
```
$ genomepy install -g data/genomes --annotation GRCz11 Ensembl
/home/s1437643/conda/lib/python3.6/site-packages/norns-0.1.2-py2.7.egg/norns/cfg.py:72: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
Traceback (most recent call last):
  File "/home/s1437643/conda/bin/genomepy", line 11, in <module>
    load_entry_point('genomepy==0.5.2', 'console_scripts', 'genomepy')()
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/s1437643/conda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/cli.py", line 38, in install
    regex=regex, invert_match=not(match), annotation=annotation)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/functions.py", line 197, in install_genome
    invert_match=invert_match)
  File "/home/s1437643/conda/lib/python3.6/site-packages/genomepy/provider.py", line 132, in download_genome
    dbname, link = self.get_genome_download_link(name, mask=mask, version=version)
TypeError: 'NoneType' object is not iterable
```

Ensembl might have changed something on their end?

**Comment by simonvh** [comment]
Thanks for reporting! I get the same error, I'll investigate.

**Comment by simonvh** [comment]
It is fixed in the current release. It's available on pypi, however, it will take a little time before the conda package is available.

**Comment by jma1991** [comment]
Great thank you very much, any estimated time I should check back on bioconda?

**Comment by simonvh** [comment]
As soon as I get the build to work on bioconda! Hopefully somewhere this week. I'll inform using this issue (and close it) once it's ready.

**Comment by simonvh** [comment]
It's now on bioconda as well.
