### ISSUE TITLE
ImportError when downloading from UCSC/Ensembl

### ISSUE THREAD

**Issue by preethiperi** [simonvh/genomepy#44]
Environment: VirtualEnv running Python 3.6.5, installed genomepy via conda
Tried to run: genomepy install hg19 UCSC --annotation
Output:
Traceback (most recent call last):
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/bin/genomepy", line 11, in <module>
    load_entry_point('genomepy==0.5.5', 'console_scripts', 'genomepy')()
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/genomepy/__init__.py", line 2, in <module>
    from genomepy.functions import (
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/genomepy/functions.py", line 13, in <module>
    from genomepy.plugin import get_active_plugins, init_plugins, activate
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/genomepy/plugin.py", line 5, in <module>
    import norns
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/norns-0.1.4-py2.7.egg/norns/__init__.py", line 1, in <module>
  File "/gpfs/commons/home/pperiyakoil/.conda/envs/gimme2/lib/python3.6/site-packages/norns-0.1.4-py2.7.egg/norns/cfg.py", line 3, in <module>
ImportError: cannot import name 'full_load'

Haven't seen any issues similar to this one.

**Comment by simonvh** [comment]
Try upgrading `pyyaml` and see if that fixes the issue.

**Comment by simonvh** [comment]
Closing due to no activity, feel free to re-open if the issue still occurs.
